version: 2

references:
  workspace: &workspace
    ~/src

  defaults: &defaults
    working_directory: *workspace
    docker:
      - image: circleci/android:api-30
    environment:
      TERM: dumb

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies


jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - *android_dependencies
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
          no_output_timeout: "15m"
      - run:
          name: Run Unit Tests
          command: ./gradlew testReleaseUnitTest
          no_output_timeout: "15m"


workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test