default_platform :android

platform :android do

  desc "Runs unit tests"
  desc "Sample usage:"
  desc "- unit_test"
  lane :unit_test do |options|
    gradle(task: "testReleaseUnitTest")
  end

  desc "Builds APK"
  lane :build_apk do
    raise "This lane is meant for CircleCI only".red unless is_ci?
    gradle(task: "assembleRelease")
  end

end
